# .github/workflows/release.yml

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  upload-assets:
    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          include:
          - os: macos-latest
            features: static_ssl
          - os: windows-latest
            features: static_ssl
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: stine-cli
          # (optional) Target triple, default is host triple.
          target: ${{ matrix.target }}
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
          features: ${{ matrix.features || '' }}
